# Generated by Django 5.0.7 on 2024-07-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_otp_created_at_remove_otp_otp_otp_otp_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_hash',
            field=models.CharField(max_length=64),
        ),
    ]
